### PR TITLE
net_gen: fix SystemNetworkGenerator NOT running the validation hooks

### PR DESCRIPTION
**Pull request by doudou**
Yes. Really.

### CODE REVIEW

**Comment by gustavoneves12** [comment]
We getting error in the following line:

```
undefined method `engine' for #<Syskit::NetworkGeneration::SystemNetworkGenerator:0x0000000f42e410> (NoMethodError)
   /home/rafaelsaback/flatfish/bir_rock/install/lib/ruby/2.1.0/transformer/syskit/extensions/system_network_generator.rb:32:in `validate_abstract_network'
```

Do we need update another package?

**Comment by doudou** [comment]
> Do we need update another package?

Sorry, I forgot to push the changes from drivers/transformer. Yes. Pushed to the roby3-async branch of drivers/transformer.

**Comment by rafaelsaback** [comment]
I've just updated the drivers/transformer branch, and the same is still happening here:

```
undefined local variable or method `engine' for #<Syskit::NetworkGeneration::SystemNetworkGenerator:0x0000000973aa38> (NameError)
    /home/rafaelsaback/flatfish/bir_rock/install/lib/ruby/2.1.0/transformer/syskit/extensions/system_network_generator.rb:32:in `validate_abstract_network'
    /home/rafaelsaback/flatfish/bir_rock/tools/syskit/lib/syskit/network_generation/system_network_generator.rb:223:in `compute_system_network'
    /home/rafaelsaback/flatfish/bir_rock/tools/syskit/lib/syskit/network_generation/system_network_generator.rb:37:in `block in generate'
```

**Comment by doudou** [comment]
> I've just updated the drivers/transformer branch,

Updated *and installed* the package ? Because there's no such thing as 'engine' [at line 32](https://github.com/Brazilian-Institute-of-Robotics/drivers-transformer/blob/roby3-async/ruby/lib/transformer/syskit/extensions/system_network_generator.rb#L32)

**Comment by rafaelsaback** [comment]
Indeed, my mistake. Now new error:

```
undefined method `compute_deployed_models' for #<Syskit::NetworkGeneration::SystemNetworkGenerator:0x00000018417428> (NoMethodError)
    /home/rafaelsaback/flatfish/bir_rock/tools/syskit/lib/syskit/exceptions.rb:290:in `block in initialize'
    /home/rafaelsaback/flatfish/bir_rock/tools/syskit/lib/syskit/exceptions.rb:288:in `each'
    /home/rafaelsaback/flatfish/bir_rock/tools/syskit/lib/syskit/exceptions.rb:288:in `initialize'
    /home/rafaelsaback/flatfish/bir_rock/tools/syskit/lib/syskit/network_generation/system_network_generator.rb:243:in `new'
    /home/rafaelsaback/flatfish/bir_rock/tools/syskit/lib/syskit/network_generation/system_network_generator.rb:243:in `verify_task_allocation'
    /home/rafaelsaback/flatfish/bir_rock/tools/syskit/lib/syskit/network_generation/system_network_generator.rb:318:in `validate_generated_network'
    /home/rafaelsaback/flatfish/bir_rock/install/lib/ruby/2.1.0/transformer/syskit/extensions/system_network_generator.rb:7:in `validate_generated_network'
    /home/rafaelsaback/flatfish/bir_rock/tools/syskit/lib/syskit/network_generation/system_network_generator.rb:227:in `compute_system_network'
    /home/rafaelsaback/flatfish/bir_rock/tools/syskit/lib/syskit/network_generation/system_network_generator.rb:37:in `block in generate'
    /home/rafaelsaback/flatfish/bir_rock/tools/roby/lib/roby/droby/event_logging.rb:21:in `log_timepoint_group'
    /home/rafaelsaback/flatfish/bir_rock/tools/syskit/lib/syskit/network_generation/system_network_generator.rb:36:in `generate'
    /home/rafaelsaback/flatfish/bir_rock/tools/syskit/lib/syskit/network_generation/engine.rb:532:in `compute_system_network'
    /home/rafaelsaback/flatfish/bir_rock/tools/syskit/lib/syskit/network_generation/engine.rb:550:in `resolve_system_network'
    /home/rafaelsaback/flatfish/bir_rock/tools/syskit/lib/syskit/network_generation/engine.rb:601:in `resolve'
    /home/rafaelsaback/flatfish/bir_rock/tools/syskit/lib/syskit/test/network_manipulation.rb:113:in `syskit_deploy'
    /home/rafaelsaback/flatfish/bir_rock/tools/syskit/lib/syskit/test/profile_assertions.rb:184:in `assert_can_deploy_together'
    /home/rafaelsaback/flatfish/bir_rock/tools/syskit/lib/syskit/test/profile_assertions.rb:159:in `block in assert_can_deploy'
    /home/rafaelsaback/flatfish/bir_rock/tools/syskit/lib/syskit/actions/profile.rb:360:in `block in each_action'
    /home/rafaelsaback/flatfish/bir_rock/tools/syskit/lib/syskit/actions/profile.rb:356:in `each'
    /home/rafaelsaback/flatfish/bir_rock/tools/syskit/lib/syskit/actions/profile.rb:356:in `each_action'
    /home/rafaelsaback/flatfish/bir_rock/tools/syskit/lib/syskit/test/profile_assertions.rb:158:in `each'
    /home/rafaelsaback/flatfish/bir_rock/tools/syskit/lib/syskit/test/profile_assertions.rb:158:in `assert_can_deploy'
    /home/rafaelsaback/flatfish/bir_rock/tools/syskit/lib/syskit/test/profile_assertions.rb:172:in `can_deploy'
    /home/rafaelsaback/flatfish/bir_rock/bundles/flat_fish/test/profiles/test_navigation.rb:43:in `block (2 levels) in <module:Profiles>'
```

**Comment by doudou** [comment]
This one you got because you have not updated the bundles .... NOT because I forgot to push the fix for it (of course).

Updated the PR with the fix for that.

**Comment by rafaelsaback** [comment]
bundles/dive was not in the proper branch, but thanks to that we've found this other out ;)

**Comment by doudou** [comment]
The bundles fixes have been merged, I'm merging this as well.

**Pull request merged**
