### PR TITLE
fix NoMethodError when reloading configuration in the shell

### PR DESCRIPTION
**Pull request by dbcesar**
The syskit.reload_config() was reporting "unknown configured method". This fix the error message, anything else need to be done?

### CODE REVIEW

**Comment by doudou** [comment]
> anything else need to be done?

Rewrite the commit message... A much better summary would be something like: "fix NoMethodError when reloading configuration in the shell"

**Comment by dbcesar** [comment]
Done.

**Comment by doudou** [comment]
Could you also add the require for test_shell_interface in test/suite.rb ? It would avoid having this problem  in the future ....

(no comment please)

**Comment by dbcesar** [comment]
Done. It caught another error. 

```
Finished in 3.772187s, 4.2416 runs/s, 9.5435 assertions/s.

  1) Error:
Syskit::ShellInterface::#restart_deployments#test_0002_restricts the deployments to the given models:


mission failed: :0x48a7e70
  owners: 
  arguments: 
    orocos_name: "stub3",
    conf: ["default"]
event 'aborted' emitted at [15:49:14.210 @1024] from 
  :0x48a7e70
    owners: 
    arguments: 
      orocos_name: "stub3",
      conf: ["default"]
  
    /home/diego/dev.bir/tools/roby/lib/roby/test/common.rb:274:in `process_events'
    /home/diego/dev.bir/tools/roby/lib/roby/test/assertions.rb:172:in `watch_events'
    /home/diego/dev.bir/tools/roby/lib/roby/test/assertions.rb:110:in `assert_event_emission'
    test/test_shell_interface.rb:92:in `block (3 levels) in <module:Syskit>'


  2) Failure:
Syskit::ShellInterface::#reload_config#test_0003_marks the tasks with changed sections as non-reusable [test/test_shell_interface.rb:52]:
Expected false to be truthy.

16 runs, 36 assertions, 1 failures, 1 errors, 0 skips
```

**Comment by dbcesar** [comment]
ping @doudou

**Comment by doudou** [comment]
OK I'll merge it as-is and fix the extra problem afterwards.

**Comment by doudou** [comment]
> fix the extra problem afterwards.

FYI https://github.com/rock-core/tools-syskit/commit/798c4ea719c1462e83f55d56af3a055467a11731

**Comment by dbcesar** [comment]
:+1:

**Pull request merged**
