### PR TITLE
mass-correct rubocop offenses and create a _todo.yml

### PR DESCRIPTION
**Pull request by doudou**
Kept the history of changes as the mass-rubocop-1 tag

- auto-generate a rubocop todo file to do progressive corrections
- auto-correct Layout/ArgumentAlignment
- auto-correct Layout/ArrayAlignment
- auto-correct Layout/AssignmentIndentation
- auto-correct Layout/BlockAlignment
- auto-correct Layout/EmptyLineAfterGuardClause
- auto-correct Layout/EmptyLineBetweenDefs
- auto-correct Layout/EmptyLines
- auto-correct Layout/EmptyLinesAroundBlockBody
- auto-correct Layout/EmptyLinesAroundClassBody
- auto-correct Layout/EmptyLinesAroundExceptionHandlingKeywords
- auto-correct Layout/EmptyLinesAroundMethodBody
- auto-correct Layout/EmptyLinesAroundModuleBody
- auto-correct Layout/IndentationConsistency
- auto-correct Layout/IndentationConsistency
- auto-correct Layout/IndentationWidth
- auto-correct Layout/LeadingCommentSpace
- auto-correct Layout/LeadingCommentSpace
- auto-correct Layout/IndentationWidth
- auto-correct Layout/DotPosition
- auto-correct Layout/EmptyLineAfterMagicComment
- auto-correct Layout/ExtraSpacing
- auto-correct Layout/SpaceAfterComma
- auto-correct Layout/SpaceAroundOperators
- auto-correct Layout/SpaceBeforeComma
- auto-correct Layout/SpaceInsideArrayLiteralBrackets
- auto-correct Layout/SpaceInsideBlockBraces
- auto-correct Layout/SpaceInsideHashLiteralBraces
- auto-correct Layout/SpaceInsideParens
- auto-correct Layout/SpaceInsideReferenceBrackets
- auto-correct Layout/Tab
- auto-correct Layout/TrailingEmptyLines
- auto-correct Layout/TrailingWhitespace
- auto-correct Layout/BlockEndNewline
- auto-correct Layout/BlockEndNewline
- auto-correct Layout/FirstArgumentIndentation
- auto-correct Layout/FirstArrayElementIndentation
- auto-correct Layout/HashAlignment
- auto-correct Layout/HeredocIndentation
- auto-correct Layout/MultilineArrayBraceLayout
- auto-correct Layout/MultilineMethodCallBraceLayout
- auto-correct Layout/MultilineMethodCallIndentation
- auto-correct Layout/MultilineMethodDefinitionBraceLayout
- auto-correct Layout/ParameterAlignment
- manually fix a number of low-count cops
- auto-correct Style/EmptyMethod
- auto-correct Style/Encoding
- auto-correct a few low-count cops
- auto-correct Style/NegatedIf
- auto-correct Style/NegatedWhile
- manually Style/InverseMethods
- auto-correct Style/MutableConstant
- auto-correct Style/ParenthesesAroundCondition
- auto-correct Style/ParallelAssignment
- auto-correct Style/PreferredHashMethods
- auto-correct Style/SafeNavigation
- auto-correct Style/SingleLineMethods
- resolve offsenses in all dynamic_data_source files
- review Lint/RedundantCopDisableDirective
- rubocop: disable Style/BlockLength for 'it' and 'describe' (specs)
- rubocop: exclude tests from the ModuleLength cop
- auto-correct Style/StringLiteralsInInterpolation
- auto-correct Style/SymbolProc
- auto-correct Style/WordArray
- manually correct low-count cops
- auto-correct Style/RedundantReturn
- auto-correct Style/RedundantInterpolation
- auto-correct Style/TrailingUnderscoreVariable
- auto-correct Style/RedundantSelf
- auto-correct Style/FrozenStringLiteralComment
- fix offenses in models/component.rb
- rake: integrate running rubocop as part of the test suite
- remove debug output
- fix leftover offenses created by rebasing on the dynamic port bindings
- add missing dependency on rubocop-rock

### CODE REVIEW

**Comment by g-arjones** [comment]
This is pretty scary... What's the test coverage?

**Comment by doudou** [comment]
> What's the test coverage?

85% or something. The auto-correct sometime fuck up the style, but I don't think they can break the semantics.

**Comment by g-arjones** [comment]
:+1:

**Comment by doudou** [comment]
> The auto-correct sometime fuck up the style

To be clearer for the record: the problem is that because some of the cops are disabled, there are auto-corrections that lead to results that are bad (but would not happen with all the cops enabled).

**Pull request merged**
